Added pre and post script execution

diff --git a/usr/bin/jpk b/usr/bin/jpk
--- a/usr/bin/jpk
+++ b/usr/bin/jpk
@@ -11,9 +11,18 @@ PKG_NAME=''
 PKG_VERSION=''
 PKG_CHECKSUM=''
 PKG_RAW_LOCATION=''
+PID_FILE="/var/run/jpk.pid"
 
+
+
+if [ -s "$PID_FILE" ]; then
+  echo "jpk already running, pid $(cat "$PID_FILE")"
+  exit 1
+fi
 
 trap jpk_do_cleanup_signal SIGHUP SIGINT SIGTERM
+
+echo -n "$$" > "$PID_FILE"
 
 #
 # cleanup functions
@@ -25,6 +34,7 @@ jpk_do_cleanup() {
     sleep "0.1"
     rm -rf "$TMP_LOCATION"
   fi
+  rm -f "$PID_FILE"
 }
 
 jpk_do_cleanup_signal() {
@@ -59,16 +69,50 @@ jpk_ensure_root() {
   fi
 }
 
+jpk_check_retval() {
+  if [ "$1" = "0" ]; then
+    echo "$2"
+  else
+    echo "$3"
+  fi
+}
+
+jpk_proces_script() {
+  if [ ! -z "$1" ]; then
+    if [ -x "$1" ]; then
+      if [ -z "$3" ] || [ "$3" = "1" ]; then
+        echo "--> Running $2 execution scrpt"
+        local rval
+        if [ "$VERBOSE" != "0" ]; then
+          bash -c "$1"
+          rval=$?
+        else
+          bash -c "$1" >/dev/null
+          rval=$?
+        fi
+        if [ "$rval" != "0" ]; then
+          echo -n "[ERROR] In executing of $2 script"
+        fi
+        return $rval
+      fi
+    else
+      echo -n "[ERROR] $2 execution script is not executable"
+      return 1
+    fi
+  fi
+  return 0
+}
 
 
 
+    
 
 jpk_sanity_check_pkg() {
 
   if [ -z "$PKG_INFO_FILE" ]; then
 
     if [ ! -s "$1" ]; then
-      echo -n "'$1' doest not exist or is empty."
+      echo -n "[ERROR] '$1' doest not exist or is empty."
       return 1
     fi
 
@@ -104,18 +148,15 @@ jpk_sanity_check_pkg() {
 
 jpk_sys_install_pkg() {
 
-  if [ -z "$2" ]; then
-    echo -n "Package name not provided, please use '$0 $1 PKG.JPK'."
+  if [ -z "$1" ]; then
+    echo -n "[ERROR] Package name not provided, please use '$0 install PKG.JPK'."
     return 1
   fi
 
-  jpk_sanity_check_pkg "$2"
+  jpk_sanity_check_pkg "$1"
+  [ "$?" != "0" ] && return 1
 
-  if [ "$?" -ne 0 ]; then
-    return 1
-  fi
-
-  echo "Installing package '$PKG_NAME' version '$PKG_VERSION'"
+  echo "-> Installing package '$PKG_NAME' version '$PKG_VERSION'"
 
   if [ -z "$PKG_CHECKSUM" ]; then
     echo "[WARN] Package doest not have a checksum" >&2
@@ -127,14 +168,39 @@ jpk_sys_install_pkg() {
     fi
   fi
 
+
+  local PRE_SCRIPT=$(jpk_read_variable_from_file "Pre-Script" )
+  local POST_SCRIPT=$(jpk_read_variable_from_file "Post-Script" )
+  local BASE_SCRIPTS=$(dirname "$PKG_INFO_FILE")
+
+  if [ ! -z "$PRE_SCRIPT" ]; then
+    PRE_SCRIPT="${BASE_SCRIPTS}/${PRE_SCRIPT}"
+  fi
+  if [ ! -z "$POST_SCRIPT" ]; then
+    POST_SCRIPT="${BASE_SCRIPTS}/${POST_SCRIPT}"
+  fi
+
+  jpk_proces_script "$PRE_SCRIPT" "Pre" 0
+  [ "$?" != "0" ] && return 1
+  jpk_proces_script "$POST_SCRIPT" "Post" 0
+  [ "$?" != "0" ] && return 1
+
+
+  jpk_proces_script "$PRE_SCRIPT" "Pre" 1
+  [ "$?" != "0" ] && return 1
+
+
   local TAR_ARGS
   [ "$VERBOSE" != "0" ] && TAR_ARGS="-v"
   ( cd / ; tar xOf "$PKG_RAW_LOCATION" "pkg.tar" | tar $TAR_ARGS -xf - )
 
   if [ "$?" != "0" ]; then
-    echo -n "Something went wrong."
-    return $?
+    echo -n "[ERROR] Something went wrong uncompressing package."
+    return 1
   fi
+
+  jpk_proces_script "$POST_SCRIPT" "Post" 1
+  [ "$?" != "0" ] && return 1
 
   return 0
 }
@@ -149,14 +215,11 @@ case "$cmd" in
   i|inst|install)
 
       jpk_ensure_root
-      jpk_sys_install_pkg $@
+      jpk_sys_install_pkg "$2"
+      retval=$?
 
-      if [ "$?" != "0" ]; then
-        echo " Aborting..."
-      else
-        echo "Package installed"
-    	retval=0
-      fi
+      jpk_check_retval $retval "Package installed" " Aborting..."
+
       ;;
 
   *)
